#!/bin/bash


if ! grep -q archlinuxcn /etc/pacman.conf;then
    echo -e '[archlinuxcn]\nServer = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch\n' |sudo tee -a /etc/pacman.conf
fi

sudo pacman -Sy --noconfirm archlinuxcn-keyring archlinux-keyring
sudo pacman -Syu --noconfirm yay git nvm rustup go neovim base base-devel cmake gcc clang gdb ninja xorg zsh tmux

sudo sed -i 's|#en_US.UTF-8|en_US.UTF-8|g' /etc/locale.gen
sudo sed -i 's|#zh_CN.UTF-8|zh_CN.UTF-8|g' /etc/locale.gen
sudo sed -i 's|#zh_CN.GBK|zh_CN.GBK|g' /etc/locale.gen

sudo locale-gen

echo -e '
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
' | sudo tee /etc/locale.conf

source /usr/share/nvm/init-nvm.sh
nvm install --lts
rustup install stable
